/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.monsterscrapper.ui;

import com.monsterscrapper.csv.GenerateCsvFile;
import com.monsterscrapper.dao.MonsterScrapperDao;
import com.monsterscrapper.dao.MonsterScrapperDaoImpl;
import com.monsterscrapper.proxy.CheckProxy;
import com.monsterscrapper.proxy.ProxyImport;
import com.monsterscrapper.thread.MainThread;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.ListSelectionModel;
import javax.swing.filechooser.FileSystemView;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

/**
 *
 * @author GLB-130
 */
public class MainPage extends javax.swing.JFrame {

    private JFrame frame;
    ApplicationContext context
            = new ClassPathXmlApplicationContext("Beans.xml");

    MonsterScrapperDao objMonsterScrapperDao
            = (MonsterScrapperDaoImpl) context.getBean("MonsterScrapperDaoImpl");
    ExecutorService executor = Executors.newFixedThreadPool(1);

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/imgres.jpg")));
        setTitle("MONSTER");
        setTitle("Monster Scrapper");
        objMonsterScrapperDao.createTables();
        loggertextArea.append("\nWelcome to monster scraper!!");
        loggertextArea.append("\nPlease upload proxies to start!!");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        titleLable = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        searchButton = new java.awt.Button();
        proxyButton = new java.awt.Button();
        keywordTextField = new javax.swing.JTextField();
        keywordLabel = new javax.swing.JLabel();
        CSVButton = new java.awt.Button();
        button2 = new java.awt.Button();
        or = new javax.swing.JLabel();
        loadKeywordsutton = new java.awt.Button();
        exitButton = new java.awt.Button();
        jPanel4 = new javax.swing.JPanel();
        loggertextArea = new java.awt.TextArea();
        jLabel2 = new javax.swing.JLabel();
        CLEAR = new java.awt.Button();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        countryList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(113, 69, 151));

        titleLable.setBackground(new java.awt.Color(255, 255, 255));
        titleLable.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        titleLable.setForeground(new java.awt.Color(255, 255, 255));
        titleLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLable.setText("Monster Scraper");
        titleLable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(titleLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(135, 135, 135))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(titleLable, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(113, 69, 151)));

        searchButton.setBackground(new java.awt.Color(113, 69, 151));
        searchButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setLabel("SEARCH");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        proxyButton.setBackground(new java.awt.Color(113, 69, 151));
        proxyButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        proxyButton.setForeground(new java.awt.Color(255, 255, 255));
        proxyButton.setLabel("LOAD PROXY");
        proxyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proxyButtonActionPerformed(evt);
            }
        });

        keywordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keywordTextFieldActionPerformed(evt);
            }
        });

        keywordLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        keywordLabel.setText("Keyword :");

        CSVButton.setBackground(new java.awt.Color(113, 69, 151));
        CSVButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        CSVButton.setForeground(new java.awt.Color(255, 255, 255));
        CSVButton.setLabel("EXPORT CSV");
        CSVButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSVButtonActionPerformed(evt);
            }
        });

        button2.setBackground(new java.awt.Color(113, 69, 151));
        button2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setLabel("STOP");
        button2.setVisible(false);
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        or.setText("OR");

        loadKeywordsutton.setBackground(new java.awt.Color(113, 69, 151));
        loadKeywordsutton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        loadKeywordsutton.setForeground(new java.awt.Color(255, 255, 255));
        loadKeywordsutton.setLabel("Load Keywords");
        loadKeywordsutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadKeywordsuttonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(113, 69, 151));
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setLabel("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(or))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(loadKeywordsutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(keywordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(keywordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(proxyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CSVButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(24, 24, 24))
                    .addComponent(keywordTextField)
                    .addComponent(keywordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CSVButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(proxyButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(or)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadKeywordsutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(113, 69, 151)));

        loggertextArea.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Process Logger:");

        CLEAR.setActionCommand("CLEAR");
        CLEAR.setBackground(new java.awt.Color(113, 69, 151));
        CLEAR.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        CLEAR.setForeground(new java.awt.Color(255, 255, 255));
        CLEAR.setLabel("CLEAR");
        CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loggertextArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(CLEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(CLEAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(loggertextArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(113, 69, 151)));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        countryList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "af:Afghanistan", "al:Albania", "dz:Algeria", "ad:Andorra", "ao:Angola", "ag:Antigua and Barbuda", "ar:Argentina", "am:Armenia", "au:Australia", "at:Austria", "az:Azerbaijan", "bs:Bahamas", "bh:Bahrain", "bd:Bangladesh", "bb:Barbados", "by:Belarus", "be:Belgium", "bz:Belize", "bj:Benin", "bm:Bermuda", "bt:Bhutan", "bo:Bolivia", "ba:Bosnia-Herzegovina", "bw:Botswana", "br:Brazil", "bn:Brunei Darussalam", "bg:Bulgaria", "bf:Burkina Faso", "bi:Burundi", "kh:Cambodia", "cm:Cameroon", "ca:Canada", "cv:Cape Verde", "ky:Cayman Islands", "cf:Central African Republic", "td:Chad", "cl:Chile", "cn:China", "co:Colombia", "km:Comoros", "cg:Congo", "cr:Costa Rica", "hr:Croatia", "cy:Cyprus", "cz:Czech Republic", "cd:Democratic Republic of Congo", "dk:Denmark", "dj:Djibouti", "dm:Dominica", "do:Dominican Republic", "ec:Ecuador", "eg:Egypt", "sv:El Salvador", "gq:Equatorial Guinea", "er:Eritrea", "ee:Estonia", "et:Ethiopia", "fk:Falkland Islands", "fj:Fiji", "fi:Finland", "fr:France", "ga:Gabon", "gm:Gambia", "ge:Georgia", "de:Germany", "gh:Ghana", "gi:Gibraltar", "gr:Greece", "gd:Grenada", "gt:Guatemala", "gn:Guinea", "gw:Guinea Bissau", "gy:Guyana", "ht:Haiti", "hn:Honduras", "hk:Hong Kong", "hu:Hungary", "is:Iceland", "in:India", "id:Indonesia", "iq:Iraq", "ie:Ireland", "il:Israel", "it:Italy", "ci:Ivory Coast", "jm:Jamaica", "jp:Japan", "jo:Jordan", "kz:Kazakhstan", "ke:Kenya", "kw:Kuwait", "kg:Kyrgyzstan", "la:Laos", "lv:Latvia", "lb:Lebanon", "ls:Lesotho", "lr:Liberia", "ly:Libya", "li:Liechtenstein", "lt:Lithuania", "lu:Luxembourg", "mo:Macau", "mk:Macedonia", "mg:Madagascar", "mw:Malawi", "my:Malaysia", "mv:Maldives", "ml:Mali", "mt:Malta", "mh:Marshall Islands", "mr:Mauritania", "mu:Mauritius", "mx:Mexico", "fm:Micronesia", "md:Moldova", "mc:Monaco", "mn:Mongolia", "ma:Morocco", "mz:Mozambique", "na:Namibia", "np:Nepal", "nl:Netherlands", "an:Netherlands Antilles", "nt:Neutral Zone", "nz:New Zealand", "ni:Nicaragua", "ne:Niger", "ng:Nigeria", "no:Norway", "om:Oman", "pk:Pakistan", "pw:Palau", "pa:Panama", "pg:Papua New Guinea", "py:Paraguay", "pe:Peru", "ph:Philippines", "pl:Poland", "pt:Portugal", "qa:Qatar", "re:Reunion (French)", "ro:Romania", "ru:Russian Federation", "rw:Rwanda", "kn:Saint Kitts & Nevis Anguilla", "lc:Saint Lucia", "st:Saint Tome and Principe", "vc:Saint Vincent & Grenadines", "ws:Samoa", "sm:San Marino", "sa:Saudi Arabia", "sn:Senegal", "yu:Serbia - Montenegro", "sc:Seychelles", "sl:Sierra Leone", "sg:Singapore", "sk:Slovakia", "si:Slovenia", "sb:Solomon Islands", "so:Somalia", "za:South Africa", "kr:South Korea", "es:Spain", "lk:Sri Lanka", "sr:Suriname", "sz:Swaziland", "se:Sweden", "ch:Switzerland", "tj:Tadjikistan", "tw:Taiwan", "tz:Tanzania", "th:Thailand", "tg:Togo", "tt:Trinidad and Tobago", "tn:Tunisia", "tr:Turkey", "tm:Turkmenistan", "ug:Uganda", "uk:UK", "ua:Ukraine", "ae:United Arab Emirates", "uy:Uruguay", "us:US", "uz:Uzbekistan", "vu:Vanuatu", "va:Vatican City", "ve:Venezuela", "vn:Vietnam", "vg:Virgin Islands (British)", "ye:Yemen", "zm:Zambia", "zw:Zimbabwe" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(countryList);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Select Location Here:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void keywordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keywordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keywordTextFieldActionPerformed

    private void proxyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proxyButtonActionPerformed
        // TODO add your handling code here:

        final JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(this);
        FileSystemView a = fc.getFileSystemView();

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            System.out.println("Selected file: " + file.getAbsolutePath());

            //file.canRead();
            System.out.println(fc.getFileSystemView());

            try {
                // What to do with the file, e.g. display it in a TextArea
                FileReader fileReader = new FileReader(file.getAbsolutePath());

                BufferedReader br = new BufferedReader(fileReader);

                String line;
                loggertextArea.append("\n Number Of Proxies ");
                while ((line = br.readLine()) != null) {
                    System.out.println(line);
                    proxyList.add(new ProxyImport(line));
                    loggertextArea.append("\n " + line);

                    countOfProxy++;

                }
                loggertextArea.append("\nNumber Of Count : " + countOfProxy);
                loggertextArea.append("\nPlease wait Checking Proxies ");

                searchButton.setEnabled(false);

                ArrayList<ProxyImport> proxyListClone = (ArrayList<ProxyImport>) proxyList.clone();
                ExecutorService executor = Executors.newFixedThreadPool(1);
                Callable worker = new CheckProxy();

                try {
                    executor.submit(worker);
                } catch (Exception ex) {
                    Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
                }

                
                System.out.println(file.getAbsolutePath());

                loggertextArea.append("\nProxy Loaded!!");

            } catch (Exception e) {
                loggertextArea.append("\n\nPlease Import a Valid .txt file!!");
                loggertextArea.append("\nProxy in the file must be in the following format!!");
                loggertextArea.append("\nProxyIP:ProxyPort:ProxyUsername:ProxyPassword");
            }
        } else {
            loggertextArea.append("\n\nPlease Import a Valid .txt file!!");
            loggertextArea.append("\nProxy in the file must be in the following format!!");
            loggertextArea.append("\nProxyIP:ProxyPort:ProxyUsername:ProxyPassword");
        }
    }//GEN-LAST:event_proxyButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
//executor = Executors.newFixedThreadPool(1);

        if (keywordTextField.getText().length() > 0) {
            keywordList.clear();
            String keyfieldvalue = keywordTextField.getText();
            String eachvalue[] = keyfieldvalue.split(",");
            for (String eachvalue1 : eachvalue) {
                keywordList.add(eachvalue1);
            }

        }
        System.out.println("proxyList:::" + proxyList.size());
        System.out.println("countOfProxy:::" + countOfProxy);
//        loggertextArea.append("\nNumber Of Proxies : " + countOfProxy);
        if (proxyList.size() > 0) {

            if (keywordList.size() > 0) {
                try {
                    if (countryList.getSelectedValuesList().isEmpty()) {
                        throw new Exception();
                    }
                    loggertextArea.append("\n process started please wait");
                    Callable worker = new MainThread(objMonsterScrapperDao, proxyList);

                    try {
                        executor.submit(worker);

                    } catch (Exception ex) {
                        Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    // im.start();
                    System.out.println("1");
                } catch (Exception e) {

                    JOptionPane.showMessageDialog(null, "Please Select Country");
                    proxyButton.setEnabled(true);
                    CSVButton.setEnabled(true);

                }

            } else {
                JOptionPane.showMessageDialog(null, "Please Select keyword");
                proxyButton.setEnabled(true);
                loadKeywordsutton.setEnabled(true);
                CSVButton.setEnabled(true);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Please Select Valid Proxy");
            proxyButton.setEnabled(true);
            CSVButton.setEnabled(true);
        }
        proxyButton.setEnabled(false);
        loadKeywordsutton.setEnabled(false);
        CSVButton.setEnabled(false);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
//        executor.shutdownNow();
        checkStop = 1;
        running = false;

        proxyButton.setEnabled(true);
        loadKeywordsutton.setEnabled(true);
        CSVButton.setEnabled(true);


    }//GEN-LAST:event_button2ActionPerformed

    private void loadKeywordsuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadKeywordsuttonActionPerformed
        // TODO add your handling code here:
        keywordList.clear();
        final JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(this);
        FileSystemView a = fc.getFileSystemView();

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            System.out.println("Selected file: " + file.getAbsolutePath());

            //file.canRead();
            System.out.println(fc.getFileSystemView());

            try {
                // What to do with the file, e.g. display it in a TextArea
                FileReader fileReader = new FileReader(file.getAbsolutePath());

                BufferedReader br = new BufferedReader(fileReader);

                String line = "";
                loggertextArea.append("\n Multiple Keywords Loaded : ");
                while ((line = br.readLine()) != null) {
                    keywordList.add(line);
                    loggertextArea.append("\n " + line);
                }

            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_loadKeywordsuttonActionPerformed

    private void CSVButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSVButtonActionPerformed
        // TODO add your handling code here:
        GenerateCsvFile objGenerateCsvFile = new GenerateCsvFile();
        try {
            String keyword = "monster1";
            try {
                keyword = keywordList.get(0);
            } catch (Exception e) {
                e.printStackTrace();
            }
            objGenerateCsvFile.excel(keyword);
        } catch (IOException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CSVButtonActionPerformed

    private void CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARActionPerformed
        // TODO add your handling code here:

        loggertextArea.setText("");
    }//GEN-LAST:event_CLEARActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(this, "Do you want to Exit???", "EXIT", 0);
        System.out.println(a);
        if (a == 0) {
            dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    public static void showDialog(Component c) {
        JOptionPane.showMessageDialog(c, "Bye Bye!");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainPage().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button CLEAR;
    public static java.awt.Button CSVButton;
    private java.awt.Button button2;
    public static javax.swing.JList countryList;
    private java.awt.Button exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel keywordLabel;
    private javax.swing.JTextField keywordTextField;
    private java.awt.Button loadKeywordsutton;
    public static java.awt.TextArea loggertextArea;
    private javax.swing.JLabel or;
    public static java.awt.Button proxyButton;
    public static java.awt.Button searchButton;
    private javax.swing.JLabel titleLable;
    // End of variables declaration//GEN-END:variables
 public static ArrayList<ProxyImport> proxyList = new ArrayList();
    public static ArrayList<String> keywordList = new ArrayList();
    public int countOfProxy = 0;
    public static int checkStop = 0;
    public static volatile boolean running = true;

}
